language: python
python:
  - "3.5"
  
# command to install dependencies
install:
  - pip install -e .
# command to run tests
script:
  - pytest --cov=./

# Push the results back to codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
